//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoMovilWA
{


    public partial class AgregarEvaluacion
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected global::System.Web.UI.WebControls.Button btnModificar;
        protected global::System.Web.UI.WebControls.Button btnRegresar;

        protected global::System.Web.UI.WebControls.DropDownList ddlTipoDocumento;
        protected global::System.Web.UI.WebControls.TextBox txtDocumento;

        protected global::System.Web.UI.WebControls.DropDownList ddlTipoDocSup;
        protected global::System.Web.UI.WebControls.TextBox txtDocumentoSup;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Label lblSuccess;
    }
}
