//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditoMovilWA
{


    public partial class TotalClientes
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txtPuntajeMin;
        protected global::System.Web.UI.WebControls.TextBox txtPuntajeMax;
        protected global::System.Web.UI.WebControls.Button btnFiltrar;
        protected global::System.Web.UI.WebControls.GridView gvClientes;
        protected global::System.Web.UI.WebControls.Button btnVerDetalle;
        protected global::System.Web.UI.WebControls.Label lblError;
    }
}
